// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optional.proto

package optional

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OptMessage struct {
	MyParam              *bool    `protobuf:"varint,1,opt,name=my_param,json=myParam,proto3,oneof" json:"my_param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptMessage) Reset()         { *m = OptMessage{} }
func (m *OptMessage) String() string { return proto.CompactTextString(m) }
func (*OptMessage) ProtoMessage()    {}
func (*OptMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_905cd112a63783c0, []int{0}
}
func (m *OptMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptMessage.Unmarshal(m, b)
}
func (m *OptMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptMessage.Marshal(b, m, deterministic)
}
func (m *OptMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptMessage.Merge(m, src)
}
func (m *OptMessage) XXX_Size() int {
	return xxx_messageInfo_OptMessage.Size(m)
}
func (m *OptMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OptMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OptMessage proto.InternalMessageInfo

func (m *OptMessage) GetMyParam() bool {
	if m != nil {
		return *m.MyParam
	}
	return false
}

func init() {
	proto.RegisterType((*OptMessage)(nil), "optional.OptMessage")
}

func init() { proto.RegisterFile("optional.proto", fileDescriptor_905cd112a63783c0) }

var fileDescriptor_905cd112a63783c0 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x2c,
	0xb9, 0xb8, 0xfc, 0x0b, 0x4a, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0xe4, 0xb8, 0x38,
	0x72, 0x2b, 0xe3, 0x0b, 0x12, 0x8b, 0x12, 0x73, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x3c, 0x18,
	0x82, 0xd8, 0x73, 0x2b, 0x03, 0x40, 0x02, 0x1d, 0x8c, 0x8c, 0x4e, 0xdc, 0x5c, 0x9c, 0xf1, 0x30,
	0x05, 0x49, 0x6c, 0x60, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xde, 0xe6, 0x85,
	0x5d, 0x00, 0x00, 0x00,
}
